version: "3"
services:
  web:
      image: nginx:latest
      container_name: nginx-samos
      restart: always
      environment:
          - VIRTUAL_HOST=www.samosrentals.rambou.gr,samosrentals.rambou.gr
          - LETSENCRYPT_HOST=www.samosrentals.rambou.gr,samosrentals.rambou.gr
          - LETSENCRYPT_EMAIL=admin@rambou.gr
      #ports:
      #    - "8080:80"
      volumes:
          - .:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      build: .
      #image: php:7-fpm
      container_name: php7_fpm
      volumes:
        - .:/code
      #  - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      restart: always
      links:
          - database
  database:
      image: mysql:5.7
      container_name: mysql
      restart: always
      volumes:
        - ./database:/var/lib/mysql
      command: '--default-authentication-plugin=mysql_native_password --lower_case_table_names=1'
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: samosrentals